spring.application.name=cobrother
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
server.port=${PORT:8080}
file.upload-dir=${UPLOAD_DIR:/tmp/uploads}
linkedin.client.id=${LINKEDIN_CLIENT_ID}
linkedin.client.secret=${LINKEDIN_CLIENT_SECRET}
linkedin.redirect.uri=${LINKEDIN_REDIRECT_URI}































































## Application Name
#spring.application.name=cobrother
#
## MongoDB Atlas
#spring.data.mongodb.uri=mongodb+srv://cobrother:WJmvgdwngXSMTZOa@cobrother.3jo1b7l.mongodb.net/cobrotherdb
#spring.data.mongodb.database=cobrotherdb
#
## Render Dynamic Port
#server.port=${PORT:8080}
#
## File Upload Location (Render temp)
#file.upload-dir=/tmp/uploads
#
#   logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
