#spring.application.name=cobrother
#
#spring.mongodb.host=localhost
#spring.mongodb.port=27017
#spring.mongodb.database=cobrotherdb



# spring.application.name=cobrother

# spring.mongodb.host=localhost
# spring.mongodb.port=27017
# spring.mongodb.database=cobrotherdb

# # File Upload Location
# file.upload-dir=D:/uploads

spring.application.name=cobrother

# MongoDB Atlas
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}
# Render dynamic port
server.port=${PORT:8080}

# File upload directory (temporary in Render)
file.upload-dir=/tmp/uploads




